// =============================================================
//  seed.js — whenever-bites
//  Pobla todas las colecciones con datos de prueba realistas
//  Uso: node seed.js
// =============================================================

const { MongoClient, ObjectId, Decimal128 } = require("mongodb");
const bcrypt = require("bcryptjs");
const dns = require("node:dns");
const fs = require("fs");
const path = require("path");

// Cargar variables de entorno desde .env.local
const envPath = path.join(__dirname, ".env.local");
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, "utf8");
  envContent.split("\n").forEach((line) => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith("#")) {
      const [key, ...valueParts] = trimmed.split("=");
      const value = valueParts.join("=").replace(/^["']|["']$/g, "");
      process.env[key.trim()] = value;
    }
  });
}

const uri = process.env.MONGODB_URI;
const dbName = process.env.MONGODB_DB || "whenever-bites";
const dnsServers = process.env.MONGODB_DNS_SERVERS;

if (!uri) throw new Error("MONGODB_URI no está definido en .env.local");

if (uri.startsWith("mongodb+srv://") && dnsServers) {
  const servers = dnsServers
    .split(",")
    .map((server) => server.trim())
    .filter(Boolean);

  if (servers.length > 0) {
    dns.setServers(servers);
  }
}

// ── Helpers ───────────────────────────────────────────────────
const dec = (v) => Decimal128.fromString(String(v));
const daysAgo = (n) => new Date(Date.now() - n * 86_400_000);

// ── IDs fijos para poder cruzar referencias ───────────────────

// Tipos de cocina
const tcIds = {
  mexicana: new ObjectId(),
  italiana: new ObjectId(),
  guatemalteca: new ObjectId(),
  americana: new ObjectId(),
  japonesa: new ObjectId(),
  china: new ObjectId(),
  thai: new ObjectId(),
  india: new ObjectId(),
  francesa: new ObjectId(),
  libanesa: new ObjectId(),
  peruana: new ObjectId(),
  vegetariana: new ObjectId(),
};

// Usuarios
const uIds = {
  admin: new ObjectId(),
  owner1: new ObjectId(),
  owner2: new ObjectId(),
  owner3: new ObjectId(),
  owner4: new ObjectId(),
  owner5: new ObjectId(),
  owner6: new ObjectId(),
  owner7: new ObjectId(),
  worker1: new ObjectId(),
  worker2: new ObjectId(),
  worker3: new ObjectId(),
  worker4: new ObjectId(),
  worker5: new ObjectId(),
  worker6: new ObjectId(),
  worker7: new ObjectId(),
  worker8: new ObjectId(),
  worker9: new ObjectId(),
  worker10: new ObjectId(),
  repartidor1: new ObjectId(),
  repartidor2: new ObjectId(),
  repartidor3: new ObjectId(),
  repartidor4: new ObjectId(),
  repartidor5: new ObjectId(),
  repartidor6: new ObjectId(),
  repartidor7: new ObjectId(),
  repartidor8: new ObjectId(),
  customer1: new ObjectId(),
  customer2: new ObjectId(),
  customer3: new ObjectId(),
  customer4: new ObjectId(),
  customer5: new ObjectId(),
  customer6: new ObjectId(),
  customer7: new ObjectId(),
  customer8: new ObjectId(),
  customer9: new ObjectId(),
  customer10: new ObjectId(),
  customer11: new ObjectId(),
  customer12: new ObjectId(),
  customer13: new ObjectId(),
  customer14: new ObjectId(),
  customer15: new ObjectId(),
};

// Restaurantes
const rIds = {
  asados: new ObjectId(),
  pizza: new ObjectId(),
  chuchito: new ObjectId(),
  burger: new ObjectId(),
  sushi: new ObjectId(),
  tacos: new ObjectId(),
  chinesica: new ObjectId(),
  thai: new ObjectId(),
  india: new ObjectId(),
  frances: new ObjectId(),
};

// Sucursales
const sIds = {
  asados_z10: new ObjectId(),
  asados_z14: new ObjectId(),
  asados_z18: new ObjectId(),
  asados_z3: new ObjectId(),
  pizza_z9: new ObjectId(),
  pizza_z2: new ObjectId(),
  pizza_z13: new ObjectId(),
  pizza_z1: new ObjectId(),
  chuchito_z4: new ObjectId(),
  chuchito_z12: new ObjectId(),
  chuchito_z8: new ObjectId(),
  burger_z1: new ObjectId(),
  burger_z6: new ObjectId(),
  burger_z4: new ObjectId(),
  burger_z5: new ObjectId(),
  sushi_z10: new ObjectId(),
  sushi_z14: new ObjectId(),
  sushi_z9: new ObjectId(),
  tacos_z8: new ObjectId(),
  tacos_z6: new ObjectId(),
  tacos_z13: new ObjectId(),
  chinesica_z3: new ObjectId(),
  chinesica_z5: new ObjectId(),
  chinesica_z10: new ObjectId(),
  thai_z7: new ObjectId(),
  thai_z14: new ObjectId(),
  india_z11: new ObjectId(),
  india_z15: new ObjectId(),
  france_z12: new ObjectId(),
  french_z15: new ObjectId(),
  french_z10: new ObjectId(),
};

// Categorías
const catIds = {
  asados_carnes: new ObjectId(),
  asados_bebidas: new ObjectId(),
  pizza_clasicas: new ObjectId(),
  pizza_especiales: new ObjectId(),
  chuchito_entradas: new ObjectId(),
  chuchito_platos: new ObjectId(),
  burger_clasicas: new ObjectId(),
  burger_combos: new ObjectId(),
  sushi_rolls: new ObjectId(),
  sushi_nigiri: new ObjectId(),
  tacos_carnitas: new ObjectId(),
  tacos_al_pastor: new ObjectId(),
  chinesica_arroces: new ObjectId(),
  chinesica_fideos: new ObjectId(),
  thai_sopas: new ObjectId(),
  thai_curry: new ObjectId(),
  india_tandoor: new ObjectId(),
  india_cúrry: new ObjectId(),
  frances_entradas: new ObjectId(),
  frances_postres: new ObjectId(),
};

// Menú items
const miIds = {
  asado_res: new ObjectId(),
  churrasco: new ObjectId(),
  limonada: new ObjectId(),
  pizza_marg: new ObjectId(),
  pizza_4q: new ObjectId(),
  chuchito: new ObjectId(),
  pepian: new ObjectId(),
  burger_simple: new ObjectId(),
  burger_triple: new ObjectId(),
  papas_fritas: new ObjectId(),
  sushi_california: new ObjectId(),
  sushi_philadelphia: new ObjectId(),
  tacos_carnitas: new ObjectId(),
  tacos_pastor: new ObjectId(),
  arroz_frito: new ObjectId(),
  pollo_chino: new ObjectId(),
  fideos_thai: new ObjectId(),
  curry_rojo: new ObjectId(),
  tandoori_pollo: new ObjectId(),
  tikka_masala: new ObjectId(),
  caldo_frances: new ObjectId(),
  croissant: new ObjectId(),
  peruana_ceviche: new ObjectId(),
  peruana_lomo: new ObjectId(),
  vegetariano_ensalada: new ObjectId(),
  vegetariano_burrata: new ObjectId(),
  libanesa_hummus: new ObjectId(),
  libanesa_shawarma: new ObjectId(),
  postre_flan: new ObjectId(),
  postre_tiramisù: new ObjectId(),
};

// ── Datos ─────────────────────────────────────────────────────

async function buildUsuarios() {
  const hash = (p) => bcrypt.hashSync(p, 10);
  return [
    {
      _id: uIds.admin,
      nombre: "Ana Administradora",
      email: "admin@wheneverbites.com",
      password_hash: hash("Admin1234!"),
      rol: "admin",
      telefono: "+502 2200-0001",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(90),
    },
    {
      _id: uIds.owner1,
      nombre: "Roberto Rosales",
      email: "roberto@asadosrosales.com",
      password_hash: hash("Owner1234!"),
      rol: "owner",
      telefono: "+502 5511-0001",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(80),
    },
    {
      _id: uIds.owner3,
      nombre: "Manuel Gutiérrez",
      email: "manuel@burgerking.com",
      password_hash: hash("Owner1234!"),
      rol: "owner",
      telefono: "+502 5511-0003",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(70),
    },
    {
      _id: uIds.owner4,
      nombre: "Yuki Tanaka",
      email: "yuki@sushiguru.com",
      password_hash: hash("Owner1234!"),
      rol: "owner",
      telefono: "+502 5511-0004",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(65),
    },
    {
      _id: uIds.worker1,
      nombre: "Mario Tzul",
      email: "mario.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0001",
      sucursal_asignada: sIds.asados_z10,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(60),
    },
    {
      _id: uIds.worker2,
      nombre: "Sofía Ajú",
      email: "sofia.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0002",
      sucursal_asignada: sIds.chuchito_z4,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(55),
    },
    {
      _id: uIds.worker3,
      nombre: "Diego Flores",
      email: "diego.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0003",
      sucursal_asignada: sIds.burger_z1,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(50),
    },
    {
      _id: uIds.worker4,
      nombre: "Andrea Morales",
      email: "andrea.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0004",
      sucursal_asignada: sIds.pizza_z9,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(48),
    },
    {
      _id: uIds.worker5,
      nombre: "Luis Rodríguez",
      email: "luis.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0005",
      sucursal_asignada: sIds.sushi_z10,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(45),
    },
    {
      _id: uIds.worker6,
      nombre: "Carmen López",
      email: "carmen.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0006",
      sucursal_asignada: sIds.tacos_z8,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(42),
    },
    {
      _id: uIds.repartidor1,
      nombre: "Pedro Cifuentes",
      email: "pedro.rep@wheneverbites.com",
      password_hash: hash("Rep12345!"),
      rol: "repartidor",
      telefono: "+502 5533-0001",
      sucursal_asignada: sIds.asados_z10,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(50),
    },
    {
      _id: uIds.repartidor2,
      nombre: "Karla Soto",
      email: "karla.rep@wheneverbites.com",
      password_hash: hash("Rep12345!"),
      rol: "repartidor",
      telefono: "+502 5533-0002",
      sucursal_asignada: sIds.pizza_z9,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(45),
    },
    {
      _id: uIds.repartidor3,
      nombre: "Roberto Moreno",
      email: "roberto.rep@wheneverbites.com",
      password_hash: hash("Rep12345!"),
      rol: "repartidor",
      telefono: "+502 5533-0003",
      sucursal_asignada: sIds.burger_z6,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(40),
    },
    {
      _id: uIds.repartidor4,
      nombre: "Alejandra Paz",
      email: "alejandra.rep@wheneverbites.com",
      password_hash: hash("Rep12345!"),
      rol: "repartidor",
      telefono: "+502 5533-0004",
      sucursal_asignada: sIds.sushi_z10,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(38),
    },
    {
      _id: uIds.repartidor5,
      nombre: "Javier Herrera",
      email: "javier.rep@wheneverbites.com",
      password_hash: hash("Rep12345!"),
      rol: "repartidor",
      telefono: "+502 5533-0005",
      sucursal_asignada: sIds.tacos_z8,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(35),
    },
    {
      _id: uIds.customer1,
      nombre: "Carlos Pérez",
      email: "carlos@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0001",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [
        {
          alias: "Casa",
          texto: "6a Avenida 12-31, Zona 10, Guatemala City",
          ubicacion: { type: "Point", coordinates: [-90.5069, 14.5994] },
          predeterminada: true,
        },
      ],
      activo: true,
      creado_en: daysAgo(40),
    },
    {
      _id: uIds.customer2,
      nombre: "María González",
      email: "maria@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0002",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [
        {
          alias: "Oficina",
          texto: "4a Calle 7-53, Zona 9, Guatemala City",
          ubicacion: { type: "Point", coordinates: [-90.514, 14.591] },
          predeterminada: true,
        },
      ],
      activo: true,
      creado_en: daysAgo(35),
    },
    {
      _id: uIds.customer3,
      nombre: "José Alvarado",
      email: "jose@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0003",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(30),
    },
    {
      _id: uIds.customer4,
      nombre: "Daniela Castillo",
      email: "daniela@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0004",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [
        {
          alias: "Casa",
          texto: "2a Calle 5-10, Zona 1, Guatemala City",
          ubicacion: { type: "Point", coordinates: [-90.5233, 14.6349] },
          predeterminada: true,
        },
      ],
      activo: true,
      creado_en: daysAgo(28),
    },
    {
      _id: uIds.customer5,
      nombre: "Fernando Gómez",
      email: "fernando@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0005",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [
        {
          alias: "Casa",
          texto: "7a Avenida 15-45, Zona 6, Guatemala City",
          ubicacion: { type: "Point", coordinates: [-90.536, 14.6231] },
          predeterminada: true,
        },
      ],
      activo: true,
      creado_en: daysAgo(25),
    },
    {
      _id: uIds.customer6,
      nombre: "Lucía Santos",
      email: "lucia.s@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0006",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(22),
    },
    {
      _id: uIds.customer7,
      nombre: "Roberto Jiménez",
      email: "roberto.j@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0007",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [
        {
          alias: "Oficina",
          texto: "3a Avenida 8-25, Zona 8, Guatemala City",
          ubicacion: { type: "Point", coordinates: [-90.522, 14.606] },
          predeterminada: true,
        },
      ],
      activo: true,
      creado_en: daysAgo(20),
    },
    {
      _id: uIds.customer8,
      nombre: "Natalia Reyes",
      email: "natalia@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0008",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(18),
    },
    {
      _id: uIds.customer9,
      nombre: "Víctor Chávez",
      email: "victor@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0009",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [
        {
          alias: "Casa",
          texto: "5a Calle 10-20, Zona 2, Guatemala City",
          ubicacion: { type: "Point", coordinates: [-90.515, 14.622] },
          predeterminada: true,
        },
      ],
      activo: true,
      creado_en: daysAgo(15),
    },
    {
      _id: uIds.customer10,
      nombre: "Sofía Mejía",
      email: "sofia.m@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0010",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(12),
    },
    {
      _id: uIds.customer11,
      nombre: "Eduardo López",
      email: "eduardo@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0011",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [
        {
          alias: "Departamento",
          texto: "12 Avenida 14-30, Zona 14, Guatemala City",
          ubicacion: { type: "Point", coordinates: [-90.4978, 14.587] },
          predeterminada: true,
        },
      ],
      activo: true,
      creado_en: daysAgo(10),
    },
    {
      _id: uIds.customer12,
      nombre: "Valentina Ruiz",
      email: "valentina@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0012",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(8),
    },
    {
      _id: uIds.customer13,
      nombre: "Alejandro Méndez",
      email: "alejandro@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0013",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [
        {
          alias: "Casa",
          texto: "9a Avenida 11-40, Zona 7, Guatemala City",
          ubicacion: { type: "Point", coordinates: [-90.525, 14.615] },
          predeterminada: true,
        },
      ],
      activo: true,
      creado_en: daysAgo(6),
    },
    {
      _id: uIds.customer14,
      nombre: "Isabella Vargas",
      email: "isabella@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0014",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(4),
    },
    {
      _id: uIds.customer15,
      nombre: "Cristian Núñez",
      email: "cristian@email.com",
      password_hash: hash("Customer1!"),
      rol: "customer",
      telefono: "+502 5544-0015",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [
        {
          alias: "Casa",
          texto: "8a Avenida 18-55, Zona 11, Guatemala City",
          ubicacion: { type: "Point", coordinates: [-90.528, 14.608] },
          predeterminada: true,
        },
      ],
      activo: true,
      creado_en: daysAgo(2),
    },
    {
      _id: uIds.owner2,
      nombre: "Lucia Rossi",
      email: "lucia@pizzanapoli.com",
      password_hash: hash("Owner1234!"),
      rol: "owner",
      telefono: "+502 5511-0002",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(75),
    },
    {
      _id: uIds.owner5,
      nombre: "Wei Chen",
      email: "wei@chinesica.com",
      password_hash: hash("Owner1234!"),
      rol: "owner",
      telefono: "+502 5511-0005",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(60),
    },
    {
      _id: uIds.owner6,
      nombre: "Pattana Suwannoi",
      email: "pattana@thaigrill.com",
      password_hash: hash("Owner1234!"),
      rol: "owner",
      telefono: "+502 5511-0006",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(55),
    },
    {
      _id: uIds.owner7,
      nombre: "Rajesh Kumar",
      email: "rajesh@indiaexpress.com",
      password_hash: hash("Owner1234!"),
      rol: "owner",
      telefono: "+502 5511-0007",
      sucursal_asignada: null,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(50),
    },
    {
      _id: uIds.worker7,
      nombre: "Gustavo Vaca",
      email: "gustavo.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0007",
      sucursal_asignada: sIds.chinesica_z3,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(40),
    },
    {
      _id: uIds.worker8,
      nombre: "Mariana Corado",
      email: "mariana.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0008",
      sucursal_asignada: sIds.thai_z7,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(38),
    },
    {
      _id: uIds.worker9,
      nombre: "Ismael Choc",
      email: "ismael.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0009",
      sucursal_asignada: sIds.india_z11,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(35),
    },
    {
      _id: uIds.worker10,
      nombre: "Patricia Cuc",
      email: "patricia.worker@wheneverbites.com",
      password_hash: hash("Worker1234!"),
      rol: "worker",
      telefono: "+502 5522-0010",
      sucursal_asignada: sIds.france_z12,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(32),
    },
    {
      _id: uIds.repartidor6,
      nombre: "Sergio Ramírez",
      email: "sergio.rep@wheneverbites.com",
      password_hash: hash("Rep12345!"),
      rol: "repartidor",
      telefono: "+502 5533-0006",
      sucursal_asignada: sIds.chinesica_z5,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(30),
    },
    {
      _id: uIds.repartidor7,
      nombre: "Monica Xol",
      email: "monica.rep@wheneverbites.com",
      password_hash: hash("Rep12345!"),
      rol: "repartidor",
      telefono: "+502 5533-0007",
      sucursal_asignada: sIds.thai_z7,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(28),
    },
    {
      _id: uIds.repartidor8,
      nombre: "Héctor Ixmucane",
      email: "hector.rep@wheneverbites.com",
      password_hash: hash("Rep12345!"),
      rol: "repartidor",
      telefono: "+502 5533-0008",
      sucursal_asignada: sIds.france_z15,
      foto_perfil_id: null,
      direcciones_guardadas: [],
      activo: true,
      creado_en: daysAgo(25),
    },
  ];
}

const tipos_cocina = [
  {
    _id: tcIds.mexicana,
    nombre: "Mexicana",
    slug: "mexicana",
    descripcion: "Tacos, burritos, enchiladas y más",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(100),
  },
  {
    _id: tcIds.italiana,
    nombre: "Italiana",
    slug: "italiana",
    descripcion: "Pizzas, pastas y risottos auténticos",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(100),
  },
  {
    _id: tcIds.guatemalteca,
    nombre: "Guatemalteca",
    slug: "guatemalteca",
    descripcion: "Pepián, jocon, chuchitos y platillos típicos",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(100),
  },
  {
    _id: tcIds.americana,
    nombre: "Americana",
    slug: "americana",
    descripcion: "Hamburguesas, hot dogs y comfort food",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(100),
  },
  {
    _id: tcIds.japonesa,
    nombre: "Japonesa",
    slug: "japonesa",
    descripcion: "Sushi, ramen y tempura",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(100),
  },
  {
    _id: tcIds.china,
    nombre: "China",
    slug: "china",
    descripcion: "Arroz frito, pollo chino, fideos cantoneses",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(95),
  },
  {
    _id: tcIds.thai,
    nombre: "Tailandesa",
    slug: "tailandesa",
    descripcion: "Curries, sopas Tom Yum y fideos Pad Thai",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(95),
  },
  {
    _id: tcIds.india,
    nombre: "India",
    slug: "india",
    descripcion: "Tandoori, curries y breads auténticos",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(95),
  },
  {
    _id: tcIds.francesa,
    nombre: "Francesa",
    slug: "francesa",
    descripcion: "Caldo de res, cruasanes y pasteles",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(90),
  },
  {
    _id: tcIds.libanesa,
    nombre: "Libanesa",
    slug: "libanesa",
    descripcion: "Hummus, shawarma y comida mediooriental",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(90),
  },
  {
    _id: tcIds.peruana,
    nombre: "Peruana",
    slug: "peruana",
    descripcion: "Ceviche, lomo saltado y ajiaco",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(88),
  },
  {
    _id: tcIds.vegetariana,
    nombre: "Vegetariana",
    slug: "vegetariana",
    descripcion: "Opciones saludables sin carnes ni pescados",
    imagen_banner_id: null,
    activa: true,
    creado_en: daysAgo(88),
  },
];

const restaurantes = [
  {
    _id: rIds.asados,
    nombre: "Asados Rosales",
    descripcion: "Auténticos asados desde 2004",
    tipo_cocina_id: tcIds.guatemalteca,
    imagen_portada_id: null,
    propietario_id: uIds.owner1,
    sitio_web: "https://asadosrosales.com",
    tags: ["carne", "asado", "familiar"],
    calificacion_promedio: dec("4.2"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(80),
  },
  {
    _id: rIds.pizza,
    nombre: "Pizza Napoli",
    descripcion: "Pizza artesanal al horno de leña",
    tipo_cocina_id: tcIds.italiana,
    imagen_portada_id: null,
    propietario_id: uIds.owner2,
    sitio_web: "https://pizzanapoli.gt",
    tags: ["pizza", "italiana", "delivery"],
    calificacion_promedio: dec("4.5"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(75),
  },
  {
    _id: rIds.chuchito,
    nombre: "El Chuchito Feliz",
    descripcion: "Comida guatemalteca tradicional, recetas de abuela",
    tipo_cocina_id: tcIds.guatemalteca,
    imagen_portada_id: null,
    propietario_id: uIds.owner1,
    sitio_web: null,
    tags: ["tipico", "guatemalteca", "economico"],
    calificacion_promedio: dec("4.7"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(70),
  },
  {
    _id: rIds.burger,
    nombre: "Burger King GT",
    descripcion: "Hamburguesas frescas al instante",
    tipo_cocina_id: tcIds.americana,
    imagen_portada_id: null,
    propietario_id: uIds.owner3,
    sitio_web: "https://burgerking.gt",
    tags: ["hamburguesa", "rapido", "americana"],
    calificacion_promedio: dec("4.3"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(62),
  },
  {
    _id: rIds.sushi,
    nombre: "Sushi Guru",
    descripcion: "Auténtico sushi japonés preparado por chef Yuki",
    tipo_cocina_id: tcIds.japonesa,
    imagen_portada_id: null,
    propietario_id: uIds.owner4,
    sitio_web: "https://sushiguru.gt",
    tags: ["sushi", "japones", "premium"],
    calificacion_promedio: dec("4.8"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(58),
  },
  {
    _id: rIds.tacos,
    nombre: "El Taquería Chapina",
    descripcion: "Tacos de carne asada y al pastor",
    tipo_cocina_id: tcIds.mexicana,
    imagen_portada_id: null,
    propietario_id: uIds.owner1,
    sitio_web: null,
    tags: ["tacos", "mexicana", "carne"],
    calificacion_promedio: dec("4.4"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(55),
  },
  {
    _id: rIds.chinesica,
    nombre: "Golden Dragon Chino",
    descripcion: "Auténtica comida china preparada en wok",
    tipo_cocina_id: tcIds.china,
    imagen_portada_id: null,
    propietario_id: uIds.owner5,
    sitio_web: "https://goldendragon.gt",
    tags: ["chino", "wok", "rapido"],
    calificacion_promedio: dec("4.1"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(52),
  },
  {
    _id: rIds.thai,
    nombre: "Thai Spice",
    descripcion: "Curries aromáticos y sopas tailandesas",
    tipo_cocina_id: tcIds.thai,
    imagen_portada_id: null,
    propietario_id: uIds.owner6,
    sitio_web: "https://thaispice.gt",
    tags: ["tailandes", "curry", "aromatico"],
    calificacion_promedio: dec("4.6"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(50),
  },
  {
    _id: rIds.india,
    nombre: "India Express",
    descripcion: "Tandoori y curries tradicionales de India",
    tipo_cocina_id: tcIds.india,
    imagen_portada_id: null,
    propietario_id: uIds.owner7,
    sitio_web: "https://indiaexpress.gt",
    tags: ["tandoori", "curry", "india"],
    calificacion_promedio: dec("4.5"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(48),
  },
  {
    _id: rIds.frances,
    nombre: "Petit Bistro Français",
    descripcion: "Gastronomía francesa en el corazón de la ciudad",
    tipo_cocina_id: tcIds.francesa,
    imagen_portada_id: null,
    propietario_id: uIds.owner2,
    sitio_web: "https://petitbistro.gt",
    tags: ["frances", "bistro", "gourmet"],
    calificacion_promedio: dec("4.8"),
    total_resenas: 0,
    activo: true,
    creado_en: daysAgo(45),
  },
];

const sucursales = [
  {
    _id: sIds.asados_z10,
    restaurante_id: rIds.asados,
    nombre: "Zona 10",
    direccion: { calle: "6a Avenida 12-31", zona: "Zona 10", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.5069, 14.5994] },
    telefono: "+502 2234-5678",
    horario: { apertura: "11:00", cierre: "23:00" },
    activa: true,
    creado_en: daysAgo(80),
  },
  {
    _id: sIds.asados_z14,
    restaurante_id: rIds.asados,
    nombre: "Zona 14",
    direccion: { calle: "15 Avenida 14-20", zona: "Zona 14", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.4978, 14.587] },
    telefono: "+502 2234-5699",
    horario: { apertura: "12:00", cierre: "22:00" },
    activa: true,
    creado_en: daysAgo(60),
  },
  {
    _id: sIds.pizza_z9,
    restaurante_id: rIds.pizza,
    nombre: "Zona 9",
    direccion: { calle: "4a Calle 7-53", zona: "Zona 9", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.514, 14.591] },
    telefono: "+502 2345-6789",
    horario: { apertura: "10:00", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(75),
  },
  {
    _id: sIds.chuchito_z4,
    restaurante_id: rIds.chuchito,
    nombre: "Zona 4",
    direccion: { calle: "Ruta 4 3-50", zona: "Zona 4", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.51, 14.603] },
    telefono: "+502 2456-7890",
    horario: { apertura: "07:00", cierre: "20:00" },
    activa: true,
    creado_en: daysAgo(70),
  },
  {
    _id: sIds.pizza_z2,
    restaurante_id: rIds.pizza,
    nombre: "Zona 2",
    direccion: { calle: "8a Avenida 22-10", zona: "Zona 2", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.505, 14.622] },
    telefono: "+502 2345-6800",
    horario: { apertura: "10:00", cierre: "23:00" },
    activa: true,
    creado_en: daysAgo(72),
  },
  {
    _id: sIds.burger_z1,
    restaurante_id: rIds.burger,
    nombre: "Zona 1",
    direccion: { calle: "3a Calle 4-28", zona: "Zona 1", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.5275, 14.6349] },
    telefono: "+502 2234-5601",
    horario: { apertura: "09:00", cierre: "22:00" },
    activa: true,
    creado_en: daysAgo(62),
  },
  {
    _id: sIds.burger_z6,
    restaurante_id: rIds.burger,
    nombre: "Zona 6",
    direccion: { calle: "9a Avenida 18-50", zona: "Zona 6", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.536, 14.6231] },
    telefono: "+502 2234-5650",
    horario: { apertura: "10:00", cierre: "23:00" },
    activa: true,
    creado_en: daysAgo(58),
  },
  {
    _id: sIds.sushi_z10,
    restaurante_id: rIds.sushi,
    nombre: "Zona 10",
    direccion: { calle: "7a Avenida 12-40", zona: "Zona 10", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.5069, 14.5994] },
    telefono: "+502 2456-7654",
    horario: { apertura: "12:00", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(58),
  },
  {
    _id: sIds.tacos_z8,
    restaurante_id: rIds.tacos,
    nombre: "Zona 8",
    direccion: { calle: "5a Calle 14-12", zona: "Zona 8", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.522, 14.606] },
    telefono: "+502 2567-8901",
    horario: { apertura: "10:00", cierre: "21:00" },
    activa: true,
    creado_en: daysAgo(55),
  },
  {
    _id: sIds.chinesica_z3,
    restaurante_id: rIds.chinesica,
    nombre: "Zona 3",
    direccion: { calle: "1a Calle 3-15", zona: "Zona 3", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.508, 14.598] },
    telefono: "+502 2384-5678",
    horario: { apertura: "11:00", cierre: "22:30" },
    activa: true,
    creado_en: daysAgo(52),
  },
  {
    _id: sIds.chinesica_z5,
    restaurante_id: rIds.chinesica,
    nombre: "Zona 5",
    direccion: { calle: "2a Avenida 8-22", zona: "Zona 5", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.512, 14.610] },
    telefono: "+502 2384-5640",
    horario: { apertura: "11:00", cierre: "22:00" },
    activa: true,
    creado_en: daysAgo(50),
  },
  {
    _id: sIds.thai_z7,
    restaurante_id: rIds.thai,
    nombre: "Zona 7",
    direccion: { calle: "6a Avenida 15-30", zona: "Zona 7", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.525, 14.612] },
    telefono: "+502 2456-1234",
    horario: { apertura: "12:00", cierre: "23:00" },
    activa: true,
    creado_en: daysAgo(50),
  },
  {
    _id: sIds.india_z11,
    restaurante_id: rIds.india,
    nombre: "Zona 11",
    direccion: { calle: "10a Avenida 20-40", zona: "Zona 11", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.528, 14.608] },
    telefono: "+502 2567-4321",
    horario: { apertura: "12:00", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(48),
  },
  {
    _id: sIds.france_z12,
    restaurante_id: rIds.frances,
    nombre: "Zona 12",
    direccion: { calle: "11a Avenida 5-50", zona: "Zona 12", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.532, 14.595] },
    telefono: "+502 2890-1234",
    horario: { apertura: "13:00", cierre: "23:59" },
    activa: true,
    creado_en: daysAgo(45),
  },
  {
    _id: sIds.french_z15,
    restaurante_id: rIds.frances,
    nombre: "Zona 15",
    direccion: { calle: "12a Avenida 12-12", zona: "Zona 15", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.545, 14.600] },
    telefono: "+502 2890-5678",
    horario: { apertura: "13:00", cierre: "23:00" },
    activa: true,
    creado_en: daysAgo(43),
  },
  // Nuevas sucursales - Asados Rosales
  {
    _id: sIds.asados_z18,
    restaurante_id: rIds.asados,
    nombre: "Zona 18",
    direccion: { calle: "3a Calle 18-45", zona: "Zona 18", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.550, 14.580] },
    telefono: "+502 2234-5710",
    horario: { apertura: "11:00", cierre: "23:00" },
    activa: true,
    creado_en: daysAgo(35),
  },
  {
    _id: sIds.asados_z3,
    restaurante_id: rIds.asados,
    nombre: "Zona 3",
    direccion: { calle: "8a Avenida 15-22", zona: "Zona 3", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.508, 14.595] },
    telefono: "+502 2234-5720",
    horario: { apertura: "11:30", cierre: "22:30" },
    activa: true,
    creado_en: daysAgo(32),
  },
  // Nuevas sucursales - Pizza Napoli
  {
    _id: sIds.pizza_z13,
    restaurante_id: rIds.pizza,
    nombre: "Zona 13",
    direccion: { calle: "2a Calle 36-80", zona: "Zona 13", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.545, 14.590] },
    telefono: "+502 2345-6810",
    horario: { apertura: "10:00", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(38),
  },
  {
    _id: sIds.pizza_z1,
    restaurante_id: rIds.pizza,
    nombre: "Zona 1 Centro",
    direccion: { calle: "5a Avenida 8-75", zona: "Zona 1", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.527, 14.635] },
    telefono: "+502 2345-6820",
    horario: { apertura: "10:30", cierre: "22:00" },
    activa: true,
    creado_en: daysAgo(30),
  },
  // Nuevas sucursales - El Chuchito Feliz
  {
    _id: sIds.chuchito_z12,
    restaurante_id: rIds.chuchito,
    nombre: "Zona 12",
    direccion: { calle: "11a Avenida 8-30", zona: "Zona 12", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.532, 14.590] },
    telefono: "+502 2456-7900",
    horario: { apertura: "07:00", cierre: "20:00" },
    activa: true,
    creado_en: daysAgo(28),
  },
  {
    _id: sIds.chuchito_z8,
    restaurante_id: rIds.chuchito,
    nombre: "Zona 8",
    direccion: { calle: "5a Calle 16-20", zona: "Zona 8", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.520, 14.605] },
    telefono: "+502 2456-7910",
    horario: { apertura: "06:30", cierre: "19:30" },
    activa: true,
    creado_en: daysAgo(25),
  },
  // Nuevas sucursales - Burger King GT
  {
    _id: sIds.burger_z4,
    restaurante_id: rIds.burger,
    nombre: "Zona 4",
    direccion: { calle: "Ruta 4 7-80", zona: "Zona 4", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.512, 14.605] },
    telefono: "+502 2234-5610",
    horario: { apertura: "09:00", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(33),
  },
  {
    _id: sIds.burger_z5,
    restaurante_id: rIds.burger,
    nombre: "Zona 5",
    direccion: { calle: "2a Avenida 12-18", zona: "Zona 5", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.515, 14.612] },
    telefono: "+502 2234-5620",
    horario: { apertura: "10:00", cierre: "23:00" },
    activa: true,
    creado_en: daysAgo(29),
  },
  // Nuevas sucursales - Sushi Guru
  {
    _id: sIds.sushi_z14,
    restaurante_id: rIds.sushi,
    nombre: "Zona 14",
    direccion: { calle: "14a Avenida 14-35", zona: "Zona 14", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.498, 14.585] },
    telefono: "+502 2456-7670",
    horario: { apertura: "12:00", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(40),
  },
  {
    _id: sIds.sushi_z9,
    restaurante_id: rIds.sushi,
    nombre: "Zona 9 Paseo Cayalá",
    direccion: { calle: "4a Calle 9-65", zona: "Zona 9", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.518, 14.588] },
    telefono: "+502 2456-7680",
    horario: { apertura: "12:30", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(37),
  },
  // Nuevas sucursales - El Taquería Chapina
  {
    _id: sIds.tacos_z6,
    restaurante_id: rIds.tacos,
    nombre: "Zona 6",
    direccion: { calle: "9a Avenida 20-55", zona: "Zona 6", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.535, 14.620] },
    telefono: "+502 2567-8910",
    horario: { apertura: "10:00", cierre: "21:30" },
    activa: true,
    creado_en: daysAgo(36),
  },
  {
    _id: sIds.tacos_z13,
    restaurante_id: rIds.tacos,
    nombre: "Zona 13",
    direccion: { calle: "2a Calle 38-75", zona: "Zona 13", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.543, 14.592] },
    telefono: "+502 2567-8920",
    horario: { apertura: "10:30", cierre: "21:00" },
    activa: true,
    creado_en: daysAgo(34),
  },
  // Nuevas sucursales - Golden Dragon Chino
  {
    _id: sIds.chinesica_z10,
    restaurante_id: rIds.chinesica,
    nombre: "Zona 10 Multicentro",
    direccion: { calle: "6a Avenida 13-50", zona: "Zona 10", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.510, 14.600] },
    telefono: "+502 2384-5690",
    horario: { apertura: "11:00", cierre: "22:30" },
    activa: true,
    creado_en: daysAgo(31),
  },
  // Nuevas sucursales - Thai Spice
  {
    _id: sIds.thai_z14,
    restaurante_id: rIds.thai,
    nombre: "Zona 14 Galerías",
    direccion: { calle: "15a Avenida 16-40", zona: "Zona 14", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.500, 14.585] },
    telefono: "+502 2456-1245",
    horario: { apertura: "12:00", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(27),
  },
  // Nuevas sucursales - India Express
  {
    _id: sIds.india_z15,
    restaurante_id: rIds.india,
    nombre: "Zona 15",
    direccion: { calle: "12a Avenida 14-50", zona: "Zona 15", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.544, 14.598] },
    telefono: "+502 2567-4330",
    horario: { apertura: "12:30", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(24),
  },
  // Nuevas sucursales - Petit Bistro Français
  {
    _id: sIds.french_z10,
    restaurante_id: rIds.frances,
    nombre: "Zona 10 Primus",
    direccion: { calle: "7a Avenida 14-20", zona: "Zona 10", ciudad: "Guatemala City" },
    ubicacion: { type: "Point", coordinates: [-90.508, 14.598] },
    telefono: "+502 2890-2345",
    horario: { apertura: "13:00", cierre: "23:30" },
    activa: true,
    creado_en: daysAgo(26),
  },
];

const categorias = [
  {
    _id: catIds.asados_carnes,
    restaurante_id: rIds.asados,
    nombre: "Carnes a la Parrilla",
    descripcion: "Cortes seleccionados al carbón",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(80),
  },
  {
    _id: catIds.asados_bebidas,
    restaurante_id: rIds.asados,
    nombre: "Bebidas",
    descripcion: "Refrescos, aguas y más",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(80),
  },
  {
    _id: catIds.pizza_clasicas,
    restaurante_id: rIds.pizza,
    nombre: "Pizzas Clásicas",
    descripcion: "Las favoritas de siempre",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(75),
  },
  {
    _id: catIds.pizza_especiales,
    restaurante_id: rIds.pizza,
    nombre: "Pizzas Especiales",
    descripcion: "Creaciones del chef",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(75),
  },
  {
    _id: catIds.chuchito_entradas,
    restaurante_id: rIds.chuchito,
    nombre: "Entradas",
    descripcion: "Para comenzar bien el día",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(70),
  },
  {
    _id: catIds.chuchito_platos,
    restaurante_id: rIds.chuchito,
    nombre: "Platos Fuertes",
    descripcion: "La cocina de Guatemala",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(70),
  },
  {
    _id: catIds.burger_clasicas,
    restaurante_id: rIds.burger,
    nombre: "Hamburguesas",
    descripcion: "Nuestras especialidades",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(62),
  },
  {
    _id: catIds.burger_combos,
    restaurante_id: rIds.burger,
    nombre: "Combos",
    descripcion: "Hamburguesa + papas + bebida",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(62),
  },
  {
    _id: catIds.sushi_rolls,
    restaurante_id: rIds.sushi,
    nombre: "Rolls",
    descripcion: "Rolls especiales",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(58),
  },
  {
    _id: catIds.sushi_nigiri,
    restaurante_id: rIds.sushi,
    nombre: "Nigiri",
    descripcion: "Nigiri tradicional",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(58),
  },
  {
    _id: catIds.tacos_carnitas,
    restaurante_id: rIds.tacos,
    nombre: "Tacos de Carnitas",
    descripcion: "Carnitas frescas al instante",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(55),
  },
  {
    _id: catIds.tacos_al_pastor,
    restaurante_id: rIds.tacos,
    nombre: "Tacos al Pastor",
    descripcion: "Carne al pastor marinada",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(55),
  },
  {
    _id: catIds.chinesica_arroces,
    restaurante_id: rIds.chinesica,
    nombre: "Arroces Fritos",
    descripcion: "Arroces con verdura y proteína",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(52),
  },
  {
    _id: catIds.chinesica_fideos,
    restaurante_id: rIds.chinesica,
    nombre: "Fideos Cantoneses",
    descripcion: "Fideos Chow Mein y Lo Mein",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(52),
  },
  {
    _id: catIds.thai_sopas,
    restaurante_id: rIds.thai,
    nombre: "Sopas Tailandesas",
    descripcion: "Tom Yum, Tom Kha y más",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(50),
  },
  {
    _id: catIds.thai_curry,
    restaurante_id: rIds.thai,
    nombre: "Curries",
    descripcion: "Curry Rojo, Verde, Amarillo",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(50),
  },
  {
    _id: catIds.india_tandoor,
    restaurante_id: rIds.india,
    nombre: "Tandoori",
    descripcion: "Pollo y carnes al tandoor",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(48),
  },
  {
    _id: catIds.india_cúrry,
    restaurante_id: rIds.india,
    nombre: "Curries Indios",
    descripcion: "Tikka Masala, Butter Chicken",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(48),
  },
  {
    _id: catIds.frances_entradas,
    restaurante_id: rIds.frances,
    nombre: "Entradas Francesas",
    descripcion: "Caldo de res, bisque y más",
    orden_display: 1,
    activa: true,
    creado_en: daysAgo(45),
  },
  {
    _id: catIds.frances_postres,
    restaurante_id: rIds.frances,
    nombre: "Postres Franceses",
    descripcion: "Flan, Tiramisù, Crème Brûlée",
    orden_display: 2,
    activa: true,
    creado_en: daysAgo(45),
  },
];

const menuitems = [
  {
    _id: miIds.asado_res,
    restaurante_id: rIds.asados,
    categoria_id: catIds.asados_carnes,
    nombre: "Asado de Res",
    descripcion: "Corte de res a las brasas con chimichurri",
    precio: dec("120.00"),
    imagen_id: null,
    tags: ["carne", "parrilla", "bestseller"],
    opciones: [
      { nombre: "Término", valores: ["3/4", "bien cocido", "al punto"], requerido: true },
      { nombre: "Acompañamiento", valores: ["papas fritas", "arroz", "ensalada"], requerido: true },
    ],
    disponible: true,
    creado_en: daysAgo(80),
  },
  {
    _id: miIds.churrasco,
    restaurante_id: rIds.asados,
    categoria_id: catIds.asados_carnes,
    nombre: "Churrasco Guatemalteco",
    descripcion: "Churrasco marinado con especias locales",
    precio: dec("95.00"),
    imagen_id: null,
    tags: ["carne", "tipico"],
    opciones: [{ nombre: "Término", valores: ["3/4", "bien cocido"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(80),
  },
  {
    _id: miIds.limonada,
    restaurante_id: rIds.asados,
    categoria_id: catIds.asados_bebidas,
    nombre: "Limonada Natural",
    descripcion: "Limonada fresca con limón criollo",
    precio: dec("18.00"),
    imagen_id: null,
    tags: ["bebida", "natural"],
    opciones: [{ nombre: "Azúcar", valores: ["normal", "poca azúcar", "sin azúcar"], requerido: false }],
    disponible: true,
    creado_en: daysAgo(80),
  },
  {
    _id: miIds.pizza_marg,
    restaurante_id: rIds.pizza,
    categoria_id: catIds.pizza_clasicas,
    nombre: "Pizza Margarita",
    descripcion: "Salsa de tomate, mozzarella fresca y albahaca",
    precio: dec("75.00"),
    imagen_id: null,
    tags: ["vegetariana", "clasica"],
    opciones: [
      { nombre: "Tamaño", valores: ["pequeña", "mediana", "grande"], requerido: true },
      { nombre: "Masa", valores: ["delgada", "gruesa"], requerido: true },
    ],
    disponible: true,
    creado_en: daysAgo(75),
  },
  {
    _id: miIds.pizza_4q,
    restaurante_id: rIds.pizza,
    categoria_id: catIds.pizza_especiales,
    nombre: "Pizza 4 Quesos",
    descripcion: "Mozzarella, gorgonzola, parmesano y provolone",
    precio: dec("110.00"),
    imagen_id: null,
    tags: ["queso", "especial", "bestseller"],
    opciones: [{ nombre: "Tamaño", valores: ["mediana", "grande"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(75),
  },
  {
    _id: miIds.chuchito,
    restaurante_id: rIds.chuchito,
    categoria_id: catIds.chuchito_entradas,
    nombre: "Chuchitos (3 unidades)",
    descripcion: "Chuchitos de pollo con recado rojo",
    precio: dec("30.00"),
    imagen_id: null,
    tags: ["tipico", "pollo", "bestseller"],
    opciones: [{ nombre: "Salsa", valores: ["verde", "roja", "ambas"], requerido: false }],
    disponible: true,
    creado_en: daysAgo(70),
  },
  {
    _id: miIds.pepian,
    restaurante_id: rIds.chuchito,
    categoria_id: catIds.chuchito_platos,
    nombre: "Pepián de Pollo",
    descripcion: "Guiso tradicional guatemalteco con pollo y verduras",
    precio: dec("65.00"),
    imagen_id: null,
    tags: ["tipico", "pollo", "sin gluten"],
    opciones: [{ nombre: "Arroz", valores: ["blanco", "frito"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(70),
  },
  {
    _id: miIds.burger_simple,
    restaurante_id: rIds.burger,
    categoria_id: catIds.burger_clasicas,
    nombre: "Hamburguesa Simple",
    descripcion: "Carne molida de calidad premium con queso",
    precio: dec("55.00"),
    imagen_id: null,
    tags: ["hamburguesa", "rapido"],
    opciones: [
      { nombre: "Término", valores: ["3/4", "bien cocido"], requerido: true },
      { nombre: "Adiciones", valores: ["bacon", "queso extra"], requerido: false },
    ],
    disponible: true,
    creado_en: daysAgo(62),
  },
  {
    _id: miIds.burger_triple,
    restaurante_id: rIds.burger,
    categoria_id: catIds.burger_clasicas,
    nombre: "Hamburguesa Triple",
    descripcion: "3 carnes, 3 quesos y todos los adereños",
    precio: dec("95.00"),
    imagen_id: null,
    tags: ["hamburguesa", "bestseller"],
    opciones: [{ nombre: "Adiciones", valores: ["bacon", "cebolla caramelizada", "piña"], requerido: false }],
    disponible: true,
    creado_en: daysAgo(62),
  },
  {
    _id: miIds.papas_fritas,
    restaurante_id: rIds.burger,
    categoria_id: catIds.burger_combos,
    nombre: "Papas Fritas",
    descripcion: "Papas fritas crujientes con sal",
    precio: dec("25.00"),
    imagen_id: null,
    tags: ["acompanamiento"],
    opciones: [{ nombre: "Tamaño", valores: ["chica", "mediana", "grande"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(62),
  },
  {
    _id: miIds.sushi_california,
    restaurante_id: rIds.sushi,
    categoria_id: catIds.sushi_rolls,
    nombre: "California Roll",
    descripcion: "Cangrejo, aguacate y pepino, cubierto con huevas de pez volador",
    precio: dec("85.00"),
    imagen_id: null,
    tags: ["sushi", "roll", "clasico"],
    opciones: [{ nombre: "Porciones", valores: ["6", "8", "10"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(58),
  },
  {
    _id: miIds.sushi_philadelphia,
    restaurante_id: rIds.sushi,
    categoria_id: catIds.sushi_rolls,
    nombre: "Philadelphia Roll",
    descripcion: "Salmón, queso crema y aguacate",
    precio: dec("105.00"),
    imagen_id: null,
    tags: ["sushi", "roll", "premium"],
    opciones: [{ nombre: "Porciones", valores: ["6", "8"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(58),
  },
  {
    _id: miIds.tacos_carnitas,
    restaurante_id: rIds.tacos,
    categoria_id: catIds.tacos_carnitas,
    nombre: "Tacos de Carnitas",
    descripcion: "Carnitas de cerdo tiradas con cebolla y cilantro",
    precio: dec("45.00"),
    imagen_id: null,
    tags: ["tacos", "mexicana", "carnitas"],
    opciones: [
      { nombre: "Cantidad", valores: ["3 tacos", "5 tacos"], requerido: true },
      { nombre: "Salsa", valores: ["verde", "roja", "habanero"], requerido: false },
    ],
    disponible: true,
    creado_en: daysAgo(55),
  },
  {
    _id: miIds.tacos_pastor,
    restaurante_id: rIds.tacos,
    categoria_id: catIds.tacos_al_pastor,
    nombre: "Tacos al Pastor",
    descripcion: "Carne marinada tipo árabe con piña",
    precio: dec("50.00"),
    imagen_id: null,
    tags: ["tacos", "mexicana", "al pastor", "bestseller"],
    opciones: [
      { nombre: "Cantidad", valores: ["3 tacos", "5 tacos"], requerido: true },
      { nombre: "Bebida", valores: ["horchata", "agua fresca", "refresco"], requerido: false },
    ],
    disponible: true,
    creado_en: daysAgo(55),
  },
  {
    _id: miIds.arroz_frito,
    restaurante_id: rIds.chinesica,
    categoria_id: catIds.chinesica_arroces,
    nombre: "Arroz Frito Especial",
    descripcion: "Arroz con pollo, camarones y verduras",
    precio: dec("65.00"),
    imagen_id: null,
    tags: ["chino", "arroz", "proteina"],
    opciones: [{ nombre: "Base", valores: ["pollo", "camarón", "cerdo"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(52),
  },
  {
    _id: miIds.pollo_chino,
    restaurante_id: rIds.chinesica,
    categoria_id: catIds.chinesica_fideos,
    nombre: "Pollo Agridulce",
    descripcion: "Pollo en salsa agridulce con verduras",
    precio: dec("60.00"),
    imagen_id: null,
    tags: ["chino", "pollo", "salsa"],
    opciones: [{ nombre: "Nivel Picante", valores: ["Suave", "Medio", "Picoso"], requerido: false }],
    disponible: true,
    creado_en: daysAgo(52),
  },
  {
    _id: miIds.fideos_thai,
    restaurante_id: rIds.thai,
    categoria_id: catIds.thai_sopas,
    nombre: "Pad Thai",
    descripcion: "Fideos de arroz con camarones, cacahuetes y germinados",
    precio: dec("70.00"),
    imagen_id: null,
    tags: ["thai", "fideos", "camarones"],
    opciones: [{ nombre: "Proteína", valores: ["Pollo", "Camarón", "Tofu"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(50),
  },
  {
    _id: miIds.curry_rojo,
    restaurante_id: rIds.thai,
    categoria_id: catIds.thai_curry,
    nombre: "Curry Rojo Tailandés",
    descripcion: "Con leche de coco, verduras y albahaca",
    precio: dec("75.00"),
    imagen_id: null,
    tags: ["thai", "curry", "especiado"],
    opciones: [{ nombre: "Picante", valores: ["Suave", "Medio", "Fuerte"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(50),
  },
  {
    _id: miIds.tandoori_pollo,
    restaurante_id: rIds.india,
    categoria_id: catIds.india_tandoor,
    nombre: "Pollo Tandoori",
    descripcion: "Pollo marinado en yogur y especias, cocido en tandoor",
    precio: dec("80.00"),
    imagen_id: null,
    tags: ["india", "tandoor", "pollo"],
    opciones: [{ nombre: "Acompañamiento", valores: ["Naan", "Arroz", "Roti"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(48),
  },
  {
    _id: miIds.tikka_masala,
    restaurante_id: rIds.india,
    categoria_id: catIds.india_cúrry,
    nombre: "Tikka Masala",
    descripcion: "Piezas de pollo en salsa de tomate y crema",
    precio: dec("85.00"),
    imagen_id: null,
    tags: ["india", "curry", "cremoso"],
    opciones: [{ nombre: "Nivel Picante", valores: ["Suave", "Fuerte"], requerido: false }],
    disponible: true,
    creado_en: daysAgo(48),
  },
  {
    _id: miIds.caldo_frances,
    restaurante_id: rIds.frances,
    categoria_id: catIds.frances_entradas,
    nombre: "Caldo de Res Francés",
    descripcion: "Caldo de res con verduras y médula ósea",
    precio: dec("90.00"),
    imagen_id: null,
    tags: ["frances", "caldo", "clasico"],
    opciones: [],
    disponible: true,
    creado_en: daysAgo(45),
  },
  {
    _id: miIds.croissant,
    restaurante_id: rIds.frances,
    categoria_id: catIds.frances_entradas,
    nombre: "Croissant Mantequilla",
    descripcion: "Croissant de masa filo con mantequilla auténtica francesa",
    precio: dec("35.00"),
    imagen_id: null,
    tags: ["frances", "pan", "desayuno"],
    opciones: [{ nombre: "Tipo", valores: ["Mantequilla", "Chocolate", "Jamón y Queso"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(45),
  },
  {
    _id: miIds.peruana_ceviche,
    restaurante_id: rIds.frances,
    categoria_id: catIds.frances_entradas,
    nombre: "Ceviche Peruano",
    descripcion: "Pescado fresco en jugo de limón con cilantro",
    precio: dec("95.00"),
    imagen_id: null,
    tags: ["peruana", "seafood", "fresco"],
    opciones: [{ nombre: "Tipo Pescado", valores: ["Corvina", "Mero", "Mixto"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(43),
  },
  {
    _id: miIds.peruana_lomo,
    restaurante_id: rIds.frances,
    categoria_id: catIds.frances_postres,
    nombre: "Lomo Saltado",
    descripcion: "Lomo de res salteado con papas criollas",
    precio: dec("110.00"),
    imagen_id: null,
    tags: ["peruana", "carne", "tipico"],
    opciones: [{ nombre: "Acompañamiento", valores: ["Arroz", "Papas"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(43),
  },
  {
    _id: miIds.vegetariano_ensalada,
    restaurante_id: rIds.chuchito,
    categoria_id: catIds.burger_combos,
    nombre: "Ensalada Vegetariana",
    descripcion: "Lechuga, tomate, zanahoria, huevo y queso",
    precio: dec("55.00"),
    imagen_id: null,
    tags: ["vegetariano", "saludable", "ensalada"],
    opciones: [{ nombre: "Aderezo", valores: ["Vinagreta", "Cesar", "Ranch"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(40),
  },
  {
    _id: miIds.vegetariano_burrata,
    restaurante_id: rIds.chuchito,
    categoria_id: catIds.pizza_especiales,
    nombre: "Burrata con Tomates",
    descripcion: "Queso burrata fresco con tomates cherry y albahaca",
    precio: dec("70.00"),
    imagen_id: null,
    tags: ["vegetariano", "queso", "gourmet"],
    opciones: [],
    disponible: true,
    creado_en: daysAgo(40),
  },
  {
    _id: miIds.libanesa_hummus,
    restaurante_id: rIds.chinesica,
    categoria_id: catIds.sushi_rolls,
    nombre: "Hummus Libanés",
    descripcion: "Pure de garbanzos con tahini y limón",
    precio: dec("40.00"),
    imagen_id: null,
    tags: ["libanesa", "vegano", "aperitivo"],
    opciones: [{ nombre: "Acompañamiento", valores: ["Pita", "Vegetales"], requerido: true }],
    disponible: true,
    creado_en: daysAgo(38),
  },
  {
    _id: miIds.libanesa_shawarma,
    restaurante_id: rIds.thai,
    categoria_id: catIds.sushi_nigiri,
    nombre: "Shawarma de Pollo",
    descripcion: "Pollo asado en pan pita con aderezos",
    precio: dec("60.00"),
    imagen_id: null,
    tags: ["libanesa", "pollo", "sandwich"],
    opciones: [{ nombre: "Salsa", valores: ["Tahini", "Tzatziki"], requerido: false }],
    disponible: true,
    creado_en: daysAgo(38),
  },
  {
    _id: miIds.postre_flan,
    restaurante_id: rIds.frances,
    categoria_id: catIds.frances_postres,
    nombre: "Flan Casero",
    descripcion: "Flan tradicional con caramelo",
    precio: dec("25.00"),
    imagen_id: null,
    tags: ["postre", "clasico", "dulce"],
    opciones: [],
    disponible: true,
    creado_en: daysAgo(45),
  },
  {
    _id: miIds.postre_tiramisù,
    restaurante_id: rIds.frances,
    categoria_id: catIds.frances_postres,
    nombre: "Tiramisù Italiano",
    descripcion: "Capas de mascarpone y café con cacao",
    precio: dec("35.00"),
    imagen_id: null,
    tags: ["postre", "italiano", "gourmet"],
    opciones: [],
    disponible: true,
    creado_en: daysAgo(45),
  },
];

// ── Generador de órdenes (50 000+) ───────────────────────────

const ESTADOS = ["pendiente", "preparando", "listo", "completado"];
const ESTADOS_DELIVERY = ["pendiente", "preparando", "listo", "en_camino", "entregado"];

const PRECIOS_MENU = new Map([
  [miIds.asado_res.toHexString(), dec("120.00")],
  [miIds.churrasco.toHexString(), dec("95.00")],
  [miIds.limonada.toHexString(), dec("18.00")],
  [miIds.pizza_marg.toHexString(), dec("75.00")],
  [miIds.pizza_4q.toHexString(), dec("110.00")],
  [miIds.chuchito.toHexString(), dec("30.00")],
  [miIds.pepian.toHexString(), dec("65.00")],
  [miIds.burger_simple.toHexString(), dec("55.00")],
  [miIds.burger_triple.toHexString(), dec("95.00")],
  [miIds.papas_fritas.toHexString(), dec("25.00")],
  [miIds.sushi_california.toHexString(), dec("85.00")],
  [miIds.sushi_philadelphia.toHexString(), dec("105.00")],
  [miIds.tacos_carnitas.toHexString(), dec("45.00")],
  [miIds.tacos_pastor.toHexString(), dec("50.00")],
  [miIds.arroz_frito.toHexString(), dec("65.00")],
  [miIds.pollo_chino.toHexString(), dec("60.00")],
  [miIds.fideos_thai.toHexString(), dec("70.00")],
  [miIds.curry_rojo.toHexString(), dec("75.00")],
  [miIds.tandoori_pollo.toHexString(), dec("80.00")],
  [miIds.tikka_masala.toHexString(), dec("85.00")],
  [miIds.caldo_frances.toHexString(), dec("90.00")],
  [miIds.croissant.toHexString(), dec("35.00")],
  [miIds.peruana_ceviche.toHexString(), dec("95.00")],
  [miIds.peruana_lomo.toHexString(), dec("110.00")],
  [miIds.vegetariano_ensalada.toHexString(), dec("55.00")],
  [miIds.vegetariano_burrata.toHexString(), dec("70.00")],
  [miIds.libanesa_hummus.toHexString(), dec("40.00")],
  [miIds.libanesa_shawarma.toHexString(), dec("60.00")],
  [miIds.postre_flan.toHexString(), dec("25.00")],
  [miIds.postre_tiramisù.toHexString(), dec("35.00")],
]);

const NOMBRES_MENU = new Map([
  [miIds.asado_res.toHexString(), "Asado de Res"],
  [miIds.churrasco.toHexString(), "Churrasco Guatemalteco"],
  [miIds.limonada.toHexString(), "Limonada Natural"],
  [miIds.pizza_marg.toHexString(), "Pizza Margarita"],
  [miIds.pizza_4q.toHexString(), "Pizza 4 Quesos"],
  [miIds.chuchito.toHexString(), "Chuchitos (3 unidades)"],
  [miIds.pepian.toHexString(), "Pepián de Pollo"],
  [miIds.burger_simple.toHexString(), "Hamburguesa Simple"],
  [miIds.burger_triple.toHexString(), "Hamburguesa Triple"],
  [miIds.papas_fritas.toHexString(), "Papas Fritas"],
  [miIds.sushi_california.toHexString(), "California Roll"],
  [miIds.sushi_philadelphia.toHexString(), "Philadelphia Roll"],
  [miIds.tacos_carnitas.toHexString(), "Tacos de Carnitas"],
  [miIds.tacos_pastor.toHexString(), "Tacos al Pastor"],
  [miIds.arroz_frito.toHexString(), "Arroz Frito Especial"],
  [miIds.pollo_chino.toHexString(), "Pollo Agridulce"],
  [miIds.fideos_thai.toHexString(), "Pad Thai"],
  [miIds.curry_rojo.toHexString(), "Curry Rojo Tailandés"],
  [miIds.tandoori_pollo.toHexString(), "Pollo Tandoori"],
  [miIds.tikka_masala.toHexString(), "Tikka Masala"],
  [miIds.caldo_frances.toHexString(), "Caldo de Res Francés"],
  [miIds.croissant.toHexString(), "Croissant Mantequilla"],
  [miIds.peruana_ceviche.toHexString(), "Ceviche Peruano"],
  [miIds.peruana_lomo.toHexString(), "Lomo Saltado"],
  [miIds.vegetariano_ensalada.toHexString(), "Ensalada Vegetariana"],
  [miIds.vegetariano_burrata.toHexString(), "Burrata con Tomates"],
  [miIds.libanesa_hummus.toHexString(), "Hummus Libanés"],
  [miIds.libanesa_shawarma.toHexString(), "Shawarma de Pollo"],
  [miIds.postre_flan.toHexString(), "Flan Casero"],
  [miIds.postre_tiramisù.toHexString(), "Tiramisù Italiano"],
]);

function buildOrden(i) {
  const esDelivery = i % 3 !== 0;
  const tipo = esDelivery ? "delivery" : "pickup";

  const configs = [
    { restaurante_id: rIds.asados, sucursal_id: sIds.asados_z10, items: [miIds.asado_res, miIds.limonada] },
    { restaurante_id: rIds.asados, sucursal_id: sIds.asados_z14, items: [miIds.churrasco, miIds.limonada] },
    { restaurante_id: rIds.pizza, sucursal_id: sIds.pizza_z9, items: [miIds.pizza_marg, miIds.pizza_4q] },
    { restaurante_id: rIds.pizza, sucursal_id: sIds.pizza_z2, items: [miIds.pizza_marg] },
    { restaurante_id: rIds.chuchito, sucursal_id: sIds.chuchito_z4, items: [miIds.chuchito, miIds.pepian] },
    { restaurante_id: rIds.burger, sucursal_id: sIds.burger_z1, items: [miIds.burger_simple, miIds.papas_fritas] },
    { restaurante_id: rIds.burger, sucursal_id: sIds.burger_z6, items: [miIds.burger_triple, miIds.papas_fritas] },
    { restaurante_id: rIds.sushi, sucursal_id: sIds.sushi_z10, items: [miIds.sushi_california, miIds.sushi_philadelphia] },
    { restaurante_id: rIds.tacos, sucursal_id: sIds.tacos_z8, items: [miIds.tacos_carnitas, miIds.tacos_pastor] },
    { restaurante_id: rIds.chinesica, sucursal_id: sIds.chinesica_z3, items: [miIds.arroz_frito, miIds.pollo_chino] },
    { restaurante_id: rIds.chinesica, sucursal_id: sIds.chinesica_z5, items: [miIds.pollo_chino] },
    { restaurante_id: rIds.thai, sucursal_id: sIds.thai_z7, items: [miIds.fideos_thai, miIds.curry_rojo] },
    { restaurante_id: rIds.india, sucursal_id: sIds.india_z11, items: [miIds.tandoori_pollo, miIds.tikka_masala] },
    { restaurante_id: rIds.frances, sucursal_id: sIds.france_z12, items: [miIds.caldo_frances, miIds.croissant] },
    { restaurante_id: rIds.frances, sucursal_id: sIds.french_z15, items: [miIds.peruana_ceviche, miIds.peruana_lomo] },
  ];
  const cfg = configs[i % configs.length];

  const usuarios = [
    uIds.customer1, uIds.customer2, uIds.customer3,
    uIds.customer4, uIds.customer5, uIds.customer6,
    uIds.customer7, uIds.customer8, uIds.customer9, uIds.customer10,
    uIds.customer11, uIds.customer12, uIds.customer13, uIds.customer14, uIds.customer15,
  ];
  const usuario_id = usuarios[i % usuarios.length];

  // Seleccionar 1 o 2 items (más variedad)
  const numItems = Math.floor(Math.random() * 2) + 1;
  const itemsSeleccionados = [];
  for (let j = 0; j < numItems; j++) {
    itemsSeleccionados.push(cfg.items[j % cfg.items.length]);
  }

  const itemsOrden = itemsSeleccionados.map((mid) => {
    const cantidad = (i % 4) + 1;
    const precioUnitario = PRECIOS_MENU.get(mid.toHexString());
    const pu = parseFloat(precioUnitario.toString());
    return {
      menuitem_id: mid,
      nombre: NOMBRES_MENU.get(mid.toHexString()),
      precio_unitario: precioUnitario,
      cantidad,
      subtotal: dec((pu * cantidad).toFixed(2)),
      opciones_elegidas: {},
    };
  });

  const monto_total = dec(itemsOrden.reduce((acc, x) => acc + parseFloat(x.subtotal.toString()), 0).toFixed(2));

  const estados = esDelivery ? ESTADOS_DELIVERY : ESTADOS;
  const estadoIdx = i % estados.length;
  const estadoActual = estados[estadoIdx];

  const creado_en = daysAgo(Math.floor(Math.random() * 60));

  const historial = estados.slice(0, estadoIdx + 1).map((estado, j) => ({
    estado,
    timestamp: new Date(creado_en.getTime() + j * 15 * 60_000),
    cambiado_por: j === 0 ? null : [uIds.worker1, uIds.worker2, uIds.worker3, uIds.worker4, uIds.worker5, uIds.worker6, uIds.worker7, uIds.worker8, uIds.worker9, uIds.worker10][Math.floor(Math.random() * 10)],
  }));

  // Direcciones variadas de entrega
  const direccionesDelivery = [
    {
      texto: "6a Avenida 12-31, Zona 10, Guatemala City",
      ubicacion: { type: "Point", coordinates: [-90.5069, 14.5994] },
    },
    {
      texto: "4a Calle 7-53, Zona 9, Guatemala City",
      ubicacion: { type: "Point", coordinates: [-90.514, 14.591] },
    },
    {
      texto: "2a Calle 5-10, Zona 1, Guatemala City",
      ubicacion: { type: "Point", coordinates: [-90.5233, 14.6349] },
    },
    {
      texto: "7a Avenida 15-45, Zona 6, Guatemala City",
      ubicacion: { type: "Point", coordinates: [-90.536, 14.6231] },
    },
    {
      texto: "3a Avenida 8-25, Zona 8, Guatemala City",
      ubicacion: { type: "Point", coordinates: [-90.522, 14.606] },
    },
    {
      texto: "5a Calle 10-20, Zona 2, Guatemala City",
      ubicacion: { type: "Point", coordinates: [-90.515, 14.622] },
    },
  ];
  const direccionEntrega = direccionesDelivery[i % direccionesDelivery.length];

  // Notas variadas
  const notasVariadas = [
    null,
    "Sin cebolla",
    "Mucho picante",
    "Bien cocido",
    "Queso extra",
    "Sin mayonesa",
    "Entregar por puerta principal",
    "Llamar antes de llegar",
    "Dejar en seguridad",
    "Contactar por WhatsApp",
    "Alergias a frutos secos",
  ];
  const notas = notasVariadas[i % notasVariadas.length];

  return {
    restaurante_id: cfg.restaurante_id,
    sucursal_id: cfg.sucursal_id,
    usuario_id,
    tipo,
    items: itemsOrden,
    monto_total,
    estado_actual: estadoActual,
    historial_estados: historial,
    direccion_entrega: esDelivery ? direccionEntrega : null,
    notas,
    creado_en,
  };
}

// ── Reseñas ───────────────────────────────────────────────────
function buildResenas() {
  return [
    {
      usuario_id: uIds.customer1,
      restaurante_id: rIds.asados,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Excelente asado, el chimichurri es increíble. Definitivamente vuelvo.",
      fotos_ids: [],
      util_count: 3,
      creado_en: daysAgo(10),
    },
    {
      usuario_id: uIds.customer2,
      restaurante_id: rIds.asados,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Muy buen sabor, un poco de espera pero valió la pena.",
      fotos_ids: [],
      util_count: 1,
      creado_en: daysAgo(8),
    },
    {
      usuario_id: uIds.customer1,
      restaurante_id: rIds.pizza,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "La mejor pizza de Guatemala City, masa perfecta.",
      fotos_ids: [],
      util_count: 7,
      creado_en: daysAgo(15),
    },
    {
      usuario_id: uIds.customer3,
      restaurante_id: rIds.pizza,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Muy rica la pizza 4 quesos. La entrega fue rápida.",
      fotos_ids: [],
      util_count: 2,
      creado_en: daysAgo(5),
    },
    {
      usuario_id: uIds.customer2,
      restaurante_id: rIds.chuchito,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "El pepián es como el de mi abuela. ¡Auténtico!",
      fotos_ids: [],
      util_count: 9,
      creado_en: daysAgo(20),
    },
    {
      usuario_id: uIds.customer3,
      restaurante_id: rIds.chuchito,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Los chuchitos más ricos que he probado.",
      fotos_ids: [],
      util_count: 4,
      creado_en: daysAgo(12),
    },
    {
      usuario_id: uIds.customer4,
      restaurante_id: rIds.burger,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Las hamburguesas están excelentes, papas crujientes.",
      fotos_ids: [],
      util_count: 2,
      creado_en: daysAgo(7),
    },
    {
      usuario_id: uIds.customer5,
      restaurante_id: rIds.burger,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "La triple es enorme y déliciosa. Muy recomendado.",
      fotos_ids: [],
      util_count: 5,
      creado_en: daysAgo(9),
    },
    {
      usuario_id: uIds.customer6,
      restaurante_id: rIds.sushi,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Sushi fresco y de calidad premium. El chef Yuki es un artista.",
      fotos_ids: [],
      util_count: 6,
      creado_en: daysAgo(14),
    },
    {
      usuario_id: uIds.customer7,
      restaurante_id: rIds.sushi,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Muy bueno, pedí el California y estaba perfectamente hecho.",
      fotos_ids: [],
      util_count: 3,
      creado_en: daysAgo(11),
    },
    {
      usuario_id: uIds.customer8,
      restaurante_id: rIds.tacos,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Los tacos al pastor están increíbles, ¡los mejor de la zona!",
      fotos_ids: [],
      util_count: 8,
      creado_en: daysAgo(6),
    },
    {
      usuario_id: uIds.customer9,
      restaurante_id: rIds.tacos,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Carnitas muy sabrosas, auténtico sabor mexicano.",
      fotos_ids: [],
      util_count: 2,
      creado_en: daysAgo(4),
    },
    {
      usuario_id: uIds.customer10,
      restaurante_id: rIds.pizza,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Pizza excelente y entrega rápida. Vuelvo a ordenar.",
      fotos_ids: [],
      util_count: 1,
      creado_en: daysAgo(3),
    },
    {
      usuario_id: uIds.customer11,
      restaurante_id: rIds.chinesica,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Arroz frito muy sabroso, pollo tierno.",
      fotos_ids: [],
      util_count: 2,
      creado_en: daysAgo(2),
    },
    {
      usuario_id: uIds.customer12,
      restaurante_id: rIds.chinesica,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "¡El mejor pollo agridulce que he comido! Muy recomendado.",
      fotos_ids: [],
      util_count: 4,
      creado_en: daysAgo(1),
    },
    {
      usuario_id: uIds.customer13,
      restaurante_id: rIds.thai,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "El Pad Thai es auténtico, sabor tradicional tailandés.",
      fotos_ids: [],
      util_count: 6,
      creado_en: daysAgo(1),
    },
    {
      usuario_id: uIds.customer14,
      restaurante_id: rIds.thai,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Curry rojo delicioso, un poco picoso pero excelente.",
      fotos_ids: [],
      util_count: 3,
      creado_en: daysAgo(2),
    },
    {
      usuario_id: uIds.customer15,
      restaurante_id: rIds.india,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Pollo tandoori perfecto, especias balanceadas.",
      fotos_ids: [],
      util_count: 5,
      creado_en: daysAgo(3),
    },
    {
      usuario_id: uIds.customer1,
      restaurante_id: rIds.india,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Tikka Masala cremoso y delicioso. Vuelvo a ordenar.",
      fotos_ids: [],
      util_count: 7,
      creado_en: daysAgo(2),
    },
    {
      usuario_id: uIds.customer2,
      restaurante_id: rIds.frances,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Caldo de res francés auténtico. El mejor de la ciudad.",
      fotos_ids: [],
      util_count: 8,
      creado_en: daysAgo(4),
    },
    {
      usuario_id: uIds.customer3,
      restaurante_id: rIds.frances,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Croissants crujientes y deliciosos. Los recomiendo.",
      fotos_ids: [],
      util_count: 3,
      creado_en: daysAgo(3),
    },
    {
      usuario_id: uIds.customer4,
      restaurante_id: rIds.asados,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Carne de excelente calidad, perfectamente cocida.",
      fotos_ids: [],
      util_count: 2,
      creado_en: daysAgo(5),
    },
    {
      usuario_id: uIds.customer5,
      restaurante_id: rIds.pizza,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Pizza margarita con ingredientes frescos.",
      fotos_ids: [],
      util_count: 1,
      creado_en: daysAgo(6),
    },
    {
      usuario_id: uIds.customer6,
      restaurante_id: rIds.burger,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Hamburguesa jugosa y fresca. ¡Excelente!",
      fotos_ids: [],
      util_count: 4,
      creado_en: daysAgo(4),
    },
    {
      usuario_id: uIds.customer7,
      restaurante_id: rIds.tacos,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Los mejores tacos de la ciudad, sin duda.",
      fotos_ids: [],
      util_count: 6,
      creado_en: daysAgo(5),
    },
    {
      usuario_id: uIds.customer8,
      restaurante_id: rIds.sushi,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Sushi fresco y bien presentado.",
      fotos_ids: [],
      util_count: 2,
      creado_en: daysAgo(7),
    },
    {
      usuario_id: uIds.customer9,
      restaurante_id: rIds.chuchito,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Comida guatemalteca auténtica, deliciosa.",
      fotos_ids: [],
      util_count: 5,
      creado_en: daysAgo(6),
    },
    {
      usuario_id: uIds.customer10,
      restaurante_id: rIds.chinesica,
      orden_id: new ObjectId(),
      calificacion: 4,
      comentario: "Comida china sabrosa y rápida.",
      fotos_ids: [],
      util_count: 1,
      creado_en: daysAgo(3),
    },
    {
      usuario_id: uIds.customer11,
      restaurante_id: rIds.thai,
      orden_id: new ObjectId(),
      calificacion: 5,
      comentario: "Experiencia tailandesa auténtica.",
      fotos_ids: [],
      util_count: 3,
      creado_en: daysAgo(2),
    },
  ];
}

// ── Índices ───────────────────────────────────────────────────
async function crearIndices(db) {
  console.log("📌 Verificando índices...");
  
  // Helper para crear índice si no existe
  async function createIndexIfNotExists(collection, keys, options) {
    try {
      await db.collection(collection).createIndex(keys, options);
      console.log(`  ✅ ${options.name} creado`);
    } catch (e) {
      if (e.code === 86 || e.message.includes("already exists")) {
        console.log(`  ℹ️  ${options.name} ya existe`);
      } else {
        throw e;
      }
    }
  }

  await createIndexIfNotExists("usuarios", { email: 1 }, { unique: true, name: "idx_usuarios_email" });
  await createIndexIfNotExists("usuarios", { rol: 1, activo: 1 }, { name: "idx_usuarios_rol_activo" });
  await createIndexIfNotExists("usuarios", { sucursal_asignada: 1 }, { name: "idx_usuarios_sucursal_asignada" });

  await createIndexIfNotExists("restaurantes", { activo: 1 }, { name: "idx_restaurantes_activo" });
  await createIndexIfNotExists("restaurantes", { activo: 1, tipo_cocina_id: 1 }, { name: "idx_restaurantes_activo_tipo_cocina" });
  await createIndexIfNotExists("restaurantes", { tags: 1 }, { name: "idx_restaurantes_tags" });
  await createIndexIfNotExists(
    "restaurantes",
    { nombre: "text", descripcion: "text" },
    { weights: { nombre: 10, descripcion: 5 }, name: "idx_restaurantes_texto", default_language: "spanish" }
  );

  await createIndexIfNotExists("sucursales", { ubicacion: "2dsphere" }, { name: "idx_sucursales_ubicacion" });
  await createIndexIfNotExists("sucursales", { restaurante_id: 1 }, { name: "idx_sucursales_restaurante" });

  await createIndexIfNotExists("tipos_cocina", { activa: 1 }, { name: "idx_tipos_cocina_activa" });

  await createIndexIfNotExists("categorias", { restaurante_id: 1, activa: 1 }, { name: "idx_categorias_restaurante_activa" });

  await createIndexIfNotExists(
    "menuitems",
    { restaurante_id: 1, categoria_id: 1, disponible: 1 },
    { name: "idx_menuitems_restaurante_categoria_disponible" }
  );
  await createIndexIfNotExists("menuitems", { tags: 1 }, { name: "idx_menuitems_tags" });
  await createIndexIfNotExists(
    "menuitems",
    { nombre: "text", descripcion: "text" },
    { weights: { nombre: 10, descripcion: 5 }, name: "idx_menuitems_texto", default_language: "spanish" }
  );

  await createIndexIfNotExists(
    "ordenes",
    { sucursal_id: 1, creado_en: -1, estado_actual: 1 },
    { name: "idx_ordenes_sucursal_fecha_estado" }
  );
  await createIndexIfNotExists("ordenes", { usuario_id: 1, estado_actual: 1 }, { name: "idx_ordenes_usuario_estado" });
  await createIndexIfNotExists(
    "ordenes",
    { sucursal_id: 1, tipo: 1, estado_actual: 1 },
    { name: "idx_ordenes_sucursal_tipo_estado" }
  );
  await createIndexIfNotExists("ordenes", { creado_en: -1 }, { name: "idx_ordenes_fecha" });
  await createIndexIfNotExists("ordenes", { restaurante_id: 1, creado_en: -1 }, { name: "idx_ordenes_restaurante_fecha" });

  await createIndexIfNotExists("resenas", { restaurante_id: 1, calificacion: -1 }, { name: "idx_resenas_restaurante_calificacion" });
  await createIndexIfNotExists("resenas", { restaurante_id: 1, creado_en: -1 }, { name: "idx_resenas_restaurante_fecha" });
  await createIndexIfNotExists("resenas", { usuario_id: 1 }, { name: "idx_resenas_usuario" });
  await createIndexIfNotExists("resenas", { creado_en: -1 }, { name: "idx_resenas_fecha" });

  console.log("✅ Verificación de índices completada");
}

// ── Main ──────────────────────────────────────────────────────
async function seed() {
  const client = new MongoClient(uri);
  try {
    await client.connect();
    const db = client.db(dbName);

    console.log(`🗄️  Conectado a: ${dbName}`);

    const colecciones = ["usuarios", "tipos_cocina", "restaurantes", "sucursales", "categorias", "menuitems", "ordenes", "resenas"];
    for (const col of colecciones) {
      await db.collection(col).deleteMany({});
    }
    console.log("🧹 Colecciones limpiadas");

    const usuarios = await buildUsuarios();
    await db.collection("usuarios").insertMany(usuarios);
    console.log(`👥 Usuarios insertados: ${usuarios.length}`);

    await db.collection("tipos_cocina").insertMany(tipos_cocina);
    console.log(`🍽️  Tipos de cocina insertados: ${tipos_cocina.length}`);

    await db.collection("restaurantes").insertMany(restaurantes);
    console.log(`🏪 Restaurantes insertados: ${restaurantes.length}`);

    await db.collection("sucursales").insertMany(sucursales);
    console.log(`📍 Sucursales insertadas: ${sucursales.length}`);

    await db.collection("categorias").insertMany(categorias);
    console.log(`📂 Categorías insertadas: ${categorias.length}`);

    await db.collection("menuitems").insertMany(menuitems);
    console.log(`🍔 Menú items insertados: ${menuitems.length}`);

    const TOTAL_ORDENES = 50_000;
    const BATCH = 1_000;
    let insertadas = 0;
    for (let i = 0; i < TOTAL_ORDENES; i += BATCH) {
      const lote = Array.from({ length: Math.min(BATCH, TOTAL_ORDENES - i) }, (_, j) => buildOrden(i + j));
      await db.collection("ordenes").insertMany(lote, { ordered: false });
      insertadas += lote.length;
      process.stdout.write(`\r📦 Órdenes insertadas: ${insertadas}/${TOTAL_ORDENES}`);
    }
    console.log();

    const resenas = buildResenas();
    await db.collection("resenas").insertMany(resenas);
    console.log(`⭐ Reseñas insertadas: ${resenas.length}`);

    for (const [rid, label] of [
      [rIds.asados, "Asados Rosales"],
      [rIds.pizza, "Pizza Napoli"],
      [rIds.chuchito, "El Chuchito Feliz"],
    ]) {
      const agg = await db.collection("resenas")
        .aggregate([{ $match: { restaurante_id: rid } }, { $group: { _id: null, avg: { $avg: "$calificacion" }, count: { $sum: 1 } } }])
        .toArray();
      if (agg.length) {
        await db.collection("restaurantes").updateOne(
          { _id: rid },
          { $set: { calificacion_promedio: dec(agg[0].avg.toFixed(1)), total_resenas: agg[0].count } }
        );
        console.log(`⭐ ${label}: ${agg[0].avg.toFixed(1)} (${agg[0].count} reseñas)`);
      }
    }

    await crearIndices(db);

    console.log("\n✅ Seed completado exitosamente");
    console.log("──────────────────────────────────────────");
    console.log("Credenciales de prueba:");
    console.log("  admin@wheneverbites.com       / Admin1234!");
    console.log("  roberto@asadosrosales.com     / Owner1234!");
    console.log("  lucia@pizzanapoli.com         / Owner1234!");
    console.log("  manuel@burgerking.com         / Owner1234!");
    console.log("  yuki@sushiguru.com            / Owner1234!");
    console.log("  mario.worker@wheneverbites.cm / Worker1234!");
    console.log("  diego.worker@wheneverbites.cm / Worker1234!");
    console.log("  pedro.rep@wheneverbites.com   / Rep12345!");
    console.log("  robero.rep@wheneverbites.com  / Rep12345!");
    console.log("  carlos@email.com              / Customer1!");
    console.log("  daniela@email.com             / Customer1!");
    console.log("──────────────────────────────────────────");
  } finally {
    await client.close();
  }
}

seed().catch((err) => {
  console.error("❌ Error en seed:", err);
  process.exit(1);
});
